
version: '3.1'


volumes:
  place_database:


services:
  place_db:
    container_name: place_db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - place_database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
